### ISSUE TITLE
Failed to access database

### ISSUE THREAD

**Issue by Muonch** [krrr/Hazama#2]
For some reason I keep getting this error when running Hazama on Arch and am not sure if it's a configuration file I need to edit or if it's some other type of issue with the program itself.  
![hazama error](https://cloud.githubusercontent.com/assets/4017828/23440159/3e0be316-fe12-11e6-9e76-7c5c61c934ae.png)

**Comment by krrr** [comment]
Did you modify any file in `~/.config/Hazama/`? If not then it's a bug.
Is your diary book file contains any private data? I want to examine it

**Comment by Muonch** [comment]
I haven't written anything in there yet since this happened the first time I opened Hazama after building it from the AUR and haven't modified anything in the home folder either. Here's [a link](https://filenurse.com/files/d35234ced7c7e41b7b887404335ffcfa.db) to the `~/.config/Hazama/` home folder file.

**Comment by krrr** [comment]
It's a bug in Python 3.6.0, it will be fixed in 3.6.1

temporary workaround: open`/usr/lib/python3.6/site-packages/hazama/db.py` and replace `self._exe('BEGIN EXCLUSIVE')` with `pass`

bug: https://bugs.python.org/issue28518

I will include this workaround in hazama 1.0.3, but suddenly i found some other bugs...

**Comment by Muonch** [comment]
Seems to work for now. Thank You!

**Comment by krrr** [comment]
just to let you know that v1.0.3 is available in AUR now
